

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MedObr.Data
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class bdEntities : DbContext
{
    public bdEntities()
        : base("name=bdEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Color> Color { get; set; }

    public virtual DbSet<Country> Country { get; set; }

    public virtual DbSet<Oborudovanie> Oborudovanie { get; set; }

    public virtual DbSet<Order> Order { get; set; }

    public virtual DbSet<Proizvoditel> Proizvoditel { get; set; }

    public virtual DbSet<Role> Role { get; set; }

    public virtual DbSet<Type> Type { get; set; }

    public virtual DbSet<User> User { get; set; }

}

}

