
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MedObr.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Oborudovanie
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Oborudovanie()
    {

        this.Order = new HashSet<Order>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public double weight { get; set; }

    public int price { get; set; }

    public byte[] photo { get; set; }

    public string description { get; set; }

    public int id_proizvoditel { get; set; }

    public int id_color { get; set; }

    public int id_type { get; set; }



    public virtual Color Color { get; set; }

    public virtual Proizvoditel Proizvoditel { get; set; }

    public virtual Type Type { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Order> Order { get; set; }

}

}
