
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MedObr.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Order
{

    public int id { get; set; }

    public int sum { get; set; }

    public int id_user { get; set; }

    public int id_oborudovanie { get; set; }

    public int count { get; set; }

    public System.DateTime date { get; set; }



    public virtual Oborudovanie Oborudovanie { get; set; }

    public virtual User User { get; set; }

}

}
